### ISSUE TITLE
v1.0 TODO

### ISSUE THREAD

**Issue by AfroThundr3007730** [AfroThundr3007730/AfroBot#1]
TODO / Roadmap
==============

* [ ] Documentation
  * [ ] Implement Changelog
  * [ ] Docstrings for all the things
  * [ ] Add Help / Usage
* [ ] Config File
  * [ ] JSON schema
  * [ ] Settings Module
  * [ ] On-wiki options
* [ ] Job management
  * [ ] Isolate core functions
  * [ ] Modularise jobs
  * [ ] Dynamic job handling
* [ ] Testing
  * [ ] Pilot on testwiki

Misc. Notes
-----------
